services:
  vban-server:
    build: .
    network_mode: "host"  # Use host networking
    environment:
      - VF_DM_API_KEY=${VF_DM_API_KEY}
      - WHISPER_SERVER_URL=${WHISPER_SERVER_URL}
      - UDP_PORT=6980
      - TCP_PORT=12345
    restart: unless-stopped
