services:
  tico-nano-udp-audio-server:
    build: .
    ports:
      - "${UDP_PORT}:6980/udp"
      - "${TCP_PORT}:12345/tcp"
    environment:
      - VF_DM_API_KEY=${VF_DM_API_KEY}
      - WHISPER_SERVER_URL=http://whisper-asr:9000
      - UDP_PORT=6980
      - TCP_PORT=12345
    restart: unless-stopped
    depends_on:
      - whisper-asr
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.tcp-server.rule=HostSNI(`myserver.com`) && Port(12345)"
      - "traefik.tcp.routers.tcp-server.entrypoints=tcp-12345"
      - "traefik.udp.routers.udp-server.rule=HostSNI(`myserver.com`) && Port(6980)"
      - "traefik.udp.routers.udp-server.entrypoints=udp-6980"


  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    # No need to expose ports to the host since it's only used internally
    expose:
      - "9000"
    environment:
      - ASR_MODEL=${WHISPER_MODEL:-base}
      - ASR_ENGINE=${WHISPER_ENGINE:-openai_whisper}
      - ASR_DEVICE=${WHISPER_DEVICE:-cpu}
    volumes:
      - whisper-cache:/root/.cache/
    restart: unless-stopped

volumes:
  whisper-cache:
    name: whisper-cache
