services:
  tico-nano-udp-audio-server:
    build: .
    network_mode: "host"
    environment:
      - VF_DM_API_KEY=${VF_DM_API_KEY}
      - WHISPER_SERVER_URL=${WHISPER_SERVER_URL}
    restart: unless-stopped
